# Generated by Django 3.2.3 on 2024-07-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_foodgramuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgramuser',
            name='avatar',
        ),
    ]
