# Generated by Django 3.2.3 on 2024-07-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ingredient_recipe_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
