# Generated by Django 3.2.3 on 2024-07-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240723_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='dimension',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='title',
            new_name='name',
        ),
    ]
