MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1
LOWER_COOKING_TIME_TRESHOLD = 15
UPPER_COOKING_TIME_TRESHOLD = 30
COOKING_TIME_RANGE = {
    'fast': (0, LOWER_COOKING_TIME_TRESHOLD),
    'medium': (LOWER_COOKING_TIME_TRESHOLD, UPPER_COOKING_TIME_TRESHOLD),
    'long': (UPPER_COOKING_TIME_TRESHOLD, 10**10)
}
COOKING_TIME_MEANS = {
    'fast': f'быстрее {LOWER_COOKING_TIME_TRESHOLD} минут' + ' ({})',
    'medium': f'быстрее {UPPER_COOKING_TIME_TRESHOLD} минут' + ' ({})',
    'long': f'дольше {UPPER_COOKING_TIME_TRESHOLD} минут' + ' ({})'
}
