version: '3'

volumes:
  pg_data:
  static:

networks:
  foodgram-network:

services:
  frontend:
    container_name: foodgram-front
    build: smash7/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.22.1
    depends_on:
      - frontend
      - backend
    ports:
      - "8800:80"
    networks:
      foodgram-network:
    volumes:
      - static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U foodgram_user -d foodgram_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
  backend:
    build: smash7/foodgram_backend:latest
    env_file:
      - .env
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8880:8880"
    volumes:
      - static:/app/static_backend
      - static:/app/media
    networks:
      - foodgram-network

