version: '3'

volumes:
  pg_data:
  static:

networks:
  foodgram-network:

services:
  frontend:
    container_name: foodgram-front
    image: smash7/foodgram_frontend:latest
    command: cp -r /app/result_build/. /static/
    volumes:
      - static:/static
  nginx:
    container_name: foodgram-proxy
    image: smash7/foodgram_nginx:latest
    depends_on:
      - frontend
      - backend
    ports:
      - "8800:80"
    networks:
      foodgram-network:
    volumes:
      - static:/static
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U foodgram_user -d foodgram_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
        foodgram-network:
  backend:
    image: smash7/foodgram_backend:latest
    env_file:
      - .env
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8880:8880"
    volumes:
      - static:/app/static_backend
      - static:/app/media
    networks:
      - foodgram-network

