# Generated by Django 3.2.3 on 2024-08-02 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240802_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
