# Generated by Django 3.2.3 on 2024-08-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='unique_code',
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_url_hash',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
