# Generated by Django 3.2.3 on 2024-08-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipeingredient_unique_recipe_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_url_hash',
        ),
    ]
