# Generated by Django 3.2.3 on 2024-08-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_short_url_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url_hash',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
